name: Waka Readme All Time

on:
  workflow_dispatch:
  schedule:
    # The first day of every month
    - cron: '0 0 * * *'

jobs:
  update-alltime-readme:
    name: WakaReadme all time DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.2.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          TIME_RANGE: all_time
          SECTION_NAME: alltime
