name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          template: markdown
          filename: README.md         # Output file
          markdown: TEMPLATE.md       # Template file
          markdown_cache: .cache      # Cache folder
          languages: yes
          plugin_notable: yes
          plugin_notable_filter: stars:>500    # Only display repositories with 500 stars or more (syntax based on GitHub search query)
          plugin_notable_repositories: yes     # Display repositories name instead of only organization name
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_achievements_display: compact   # Use compact display
          plugin_support: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS" # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                                # Hides all languages less than 2%
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used languages stats
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)n
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                               # Limit recently used stats to last week
          commits_authoring: jsantanders@outlook.com                    # Surnames or email addresses used to identify your commits
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
