name: Waka Readme Weekly

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-weekly-readme:
    name: WakaReadme weekly DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.2.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          TIME_RANGE: last_7_days
          SECTION_NAME: weekly
          LANG_COUNT: 5
